### ISSUE TITLE
Add the V4M_LOG_NS and V4M_MON_NS variables

### ISSUE THREAD

**Issue by chrzaszczg** [sassoftware/viya4-deployment#109] opened 2021-06-23 15:19 UTC
When deploying SAS Viya Monitoring for Kubernetes, it is great to be able to change the namespaces where logging and/or monitoring are deployed.
The default namespaces are monitoring and logging but these name are too generic and it will be great to be able to use namespaces of our choice, or deployed both cluster monitoring and logging in a single namespace.
This option is available when we deploy it manually.
Thanks in advance.

**Comment by NormJohnIV** [comment] 2021-06-23 21:45
Duplicate of https://github.com/sassoftware/viya4-deployment/issues/108

**Closed by NormJohnIV** 2021-06-23 21:45 UTC
Labels: duplicate
